export * from './components/SetterCollapse'
export { ColorSelect } from './ColorSelect'
export { UiSizeInput } from './UiSizeInput'
export { FontStyleButton } from './FontStyleButton'
export { TextAlign } from './TextAlign'
export { BackgroundSetter } from './BackgroundSetter'
export { PaletteSetter } from './PaletteSetter'
export { PaletteSelect } from './components/PaletteSelect'
// export type * from '@/types'
